CREATE TABLE IF NOT EXISTS users (
	id INT CHECK (id > 0) NOT NULL GENERATED ALWAYS AS IDENTITY,
	firstName VARCHAR(255) NOT NULL,
	lastName VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	createdAt TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,

	PRIMARY KEY (id),
	UNIQUE (email)
);